name: 'Deploy .net core backend'
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'NasiPolitici/**'
env:
  region: ${{ secrets.AWS_REGION }}
  repository: ${{ secrets.AWS_REPOSITORY }}
  serviceName: 'nasi-politici'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Login to Repository'
        run: |
          aws ecr get-login-password --region ${{ env.region }} | docker login --username AWS --password-stdin ${{ env.repository }}/${{ env.serviceName }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: 'Build Docker image'
        run: |
          docker build -t ${{ env.serviceName }} .
        working-directory: 'NasiPolitici'
      - name: 'Push Docker image to repository'
        run: |
          docker tag ${{ env.serviceName }}:latest ${{ env.repository }}/${{ env.serviceName }}:latest
          docker push ${{ env.repository }}/${{ env.serviceName }}:latest
      - name: 'Redeploy to ECS'
        run: |
          aws --region ${{ env.region }} ecs update-service --cluster ${{ env.serviceName }} --service ${{ env.serviceName }} --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
